#!/bin/bash
# Bash Menu Script Example

# Text Formating
txtgrn=$(tput setaf 2) # Green
txtwht=$(tput setaf 7) # White
txtblu=$(tput setaf 4) # Blue
txtrst=$(tput sgr0) # Text reset.
txtbold=$(tput bold) # Text Bold
txtred=$(tput setaf 1) # red
txtyellow=$(tput setaf 3) # yellow

TXT_START="$txtblu[START]$txtrst";
TXT_FINISH="${txtyellow}FINISHED${txtrst}";
TXT_ERROR="${txtred}ERROR OCCURRED:${txtrst}";

# project specific settings
PROJ_NAME=''
PROJ_PATH=''

DEPLOYMENT_FULL_PATH=''
BUILD_COMMAND=''
RUN_COMMAND=''
HOST_NAME=''
RC_NAME=''


#Handle error status
function error_exit
{
 echo "$TXT_ERROR$1$txtrst" | 1>&2
 exit 1
}

function selectHost() {
  echo ""
  echo ${txtyellow}
  echo "PLease select Host .."
  echo "1. Staging"
  echo "2. Testing"
  echo "3. Staging [Ireland]"
  echo "4. Dev4Proxy"
  echo "---------------"
  echo "99. ALL"
  
  echo ${txtrst}
  while :
  do
    read INPUT_STRING
    case $INPUT_STRING in
	  1)
      HOST_NAME="staging"
      break
		  ;;
    2)
      HOST_NAME="testing"
      break
	  	;;
    3)
      HOST_NAME="stagingnew"
      break
	  	;;  
    99)
      HOST_NAME="applicationstack"
      break
	  	;;
    4)
      HOST_NAME="dev4proxy"
      break
	  	;;  
    *)
		  echo "Wrong input supplied"
		  ;;
     esac
  done  
}

function selectProject() {
  
  echo "Please select the project ..."
  echo ${txtyellow}
  echo "1. hydrazine"
  echo "2. nitrous"
  echo "3. nemo"
  echo "4. opticalshrink"
  echo "5. atom"
  echo "6. fluorescence"
  echo "7. magnumopus"
  echo "8. sankatmochan"
  echo "9. discovery"
  echo ${txtrst}
while :
do
  read INPUT_STRING
  case $INPUT_STRING in
	1)
		echo "Deploying Hydrazine!"
    PROJ_NAME="hydrazine"
    break
		;;
  3)
		echo "Deploying Nemo!"
    PROJ_NAME="nemo"
    break
		;;
  4)
		echo "Deploying OpticalShrink!"
    PROJ_NAME="opticalshrink"
    break
		;;
  5)
		echo "Deploying Atom!"
    PROJ_NAME="atom"
    break
		;;
  6)
		echo "Deploying Fluorescence!"
    PROJ_NAME="fluorescence"
    break
		;;
  7)
		echo "Deploying MagnumOpus!"
    PROJ_NAME="magnumopus"
    break
		;;
  8)
		echo "Deploying SankatMochan!"
    PROJ_NAME="sankatmochan"
    break
		;;
  9)
		echo "Deploying Discovery!"
    PROJ_NAME="discovery"
    break
    ;;      
	*)
		echo "Wrong input supplied"
		;;
  esac
done
}


 function fetchTags() {
  #echo "Fetching RC list from: ";
  #echo "git fetch --tags git@github.com:BoutiqaatREPO/$PROJ_NAME.git";
   git fetch --tags git@github.com:BoutiqaatREPO/$PROJ_NAME.git 
   if [ "$?" != "0" ]; then
      return 1
    fi
    return 0
 } 

 function takeProjcheckout() {
    rm -rf "/workspace/$PROJ_NAME"    
    cd "/workspace"
    git clone git@github.com:BoutiqaatREPO/$PROJ_NAME.git
    if [ "$?" != "0" ]; then
      return 1
    fi
    return 0
 }

 function showExistingRc() {
  echo "fetching RC list"
  echo "Please wait ...."

  
  cd "/workspace/$PROJ_NAME"
  
  fetchTags
  if [ "$?" != "0" ]; then
      cd ..
      takeProjcheckout
      cd "/workspace/$PROJ_NAME"
      fetchTags
      if [ "$?" != "0" ]; then
       return 1
      fi
  fi

  echo "Running git fetch"

  echo ${txtyellow}
  git tag | sort -V | tail -10
  echo ${txtrst}
  return 0
}

function askForRcName() {
  read -p "Enter RC Name to be deployed [ $PROJ_NAME ]: "  RC_NAME
  if [ "$?" != "0" ]; then
    return 1
  fi
  return 0
}

function deploy() {
    echo "Checking out $RC_NAME"
    git checkout $RC_NAME
    if [ "$?" != "0" ]; then
      return 1
    fi
    echo -e "Tag : $RC_NAME \n\n" > version.txt
    git log -1 >> version.txt
    if [ "$?" != "0" ]; then
      return 1
    fi
    
    docker build --tag=boutiqaat/$PROJ_NAME:$RC_NAME . > /dev/null
    if [ "$?" != "0" ]; then
      return 1
    fi
    docker save boutiqaat/$PROJ_NAME:$RC_NAME -o $PROJ_NAME-$RC_NAME.tar
    if [ "$?" != "0" ]; then
      return 1
    fi
    
    mkdir -p /images/$PROJ_NAME/
    if [ "$?" != "0" ]; then
      return 1
    fi
    mv /workspace/$PROJ_NAME/$PROJ_NAME-$RC_NAME.tar /images/$PROJ_NAME/$PROJ_NAME-$RC_NAME.tar
    if [ "$?" != "0" ]; then
      return 1
    fi

    ANSIBLE_NOCOWS=1 ansible-playbook  /opt/ansible/playbooks/boutiqaat/deploydocker.yml \
    --extra-vars "binpath=/images/ hosts=$HOST_NAME \
    rcname=$RC_NAME ansible_become_pass=master projname=$PROJ_NAME"
    if [ "$?" != "0" ]; then
      return 1
    fi

}

function showsuccess() {
  /usr/games/cowsay -f moofasa ${txtyellow}It seems you just got it correct.${txtrst}
}

function main() {
    selectProject || error_exit "Not a valid project:("
    selectHost || error_exit "Not a valid host:("

    showExistingRc || error_exit "Could Not Show RC list :("
    askForRcName || error_exit "Could Not Show RC list :("
    deploy || error_exit "Deployment failed :("
    showsuccess
    
}

main
