#!/bin/bash
mkdir -p /workspace
mkdir -p /images

mkdir -p /usr/local/boutiqaat/hydrazine/src/github.com/BoutiqaatREPO
mkdir -p /usr/local/boutiqaat/nitrous/src/github.com/BoutiqaatREPO
mkdir -p /usr/local/boutiqaat/nemo/src/github.com/BoutiqaatREPO
mkdir -p /usr/local/boutiqaat/opticalshrink/src/github.com/BoutiqaatREPO
mkdir -p /usr/local/boutiqaat/atom/src/github.com/BoutiqaatREPO
mkdir -p /usr/local/boutiqaat/fluorescence/src/github.com/BoutiqaatREPO
mkdir -p /usr/local/boutiqaat/magnumopus/src/github.com/BoutiqaatREPO
mkdir -p /usr/local/boutiqaat/sankatmochan/src/github.com/BoutiqaatREPO
mkdir -p /usr/local/boutiqaat/discovery/src/github.com/BoutiqaatREPO